"""112

Revision ID: 497c64eabb01
Revises: ca643bb72fb9
Create Date: 2023-01-05 08:16:29.373375

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '497c64eabb01'
down_revision = 'ca643bb72fb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
