"""11234

Revision ID: b30ed91d5f83
Revises: 497c64eabb01
Create Date: 2023-01-05 08:18:10.328986

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b30ed91d5f83'
down_revision = '497c64eabb01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
